#!/bin/bash

echo "Deploying BLUE version..."
kubectl apply -f blue_deployment.yaml

echo "Deploying GREEN version..."
kubectl apply -f green_deployment.yaml

echo "Applying Service..."
kubectl apply -f kubeservice.yaml

echo "Checking GREEN deployment logs..."
GREEN_POD=$(kubectl get pods -l version=green -o jsonpath="{.items[0].metadata.name}")
kubectl logs "$GREEN_POD"
